const router = require('express').Router();
const { protect } = require('../middleware/auth');
const c = require('../controllers/congNoController');
router.use(protect);
router.get('/summary',               c.summary);
router.get('/khach',                  c.khachNo);
router.get('/khach/:maKhachHang/hoa-don', c.hoaDonNo);
router.get('/ncc',                    c.nccNo);
router.get('/ncc/:maNhaCungCap/phieu-nhap', c.phieuNhapNo);
module.exports = router;
