const router = require('express').Router();
const { protect } = require('../middleware/auth');
const c = require('../controllers/hoaDonController');
router.use(protect);
router.get('/',    c.getAll);
router.get('/:id', c.getOne);
router.post('/',   c.create);
router.put('/:id/chi-tiet', c.updateChiTiet);
router.put('/:id', c.update);
router.delete('/:id', c.cancel);
router.post('/:id/payment', c.addPayment);
module.exports = router;
