const router = require('express').Router();
const { protect, requirePermission } = require('../middleware/auth');
const c = require('../controllers/phieuNhapController');
router.use(protect);
router.get('/',    requirePermission('nhap_hang'), c.getAll);
router.get('/:id', requirePermission('nhap_hang'), c.getOne);
router.post('/',   requirePermission('nhap_hang'), c.create);
router.put('/:id', requirePermission('nhap_hang'), c.update);
router.post('/:id/payment', requirePermission(['nhap_hang', 'xem_cong_no']), c.addPayment);
module.exports = router;
